### ISSUE TITLE
attach-extended in build.gradle

### ISSUE THREAD

**Issue by websystemtechnology** [gluonhq/AttachExtended#2]
Sorry, I reopen the ticket as the error is still present. I have a gradle project, not maven, and therefore I don't have the pom.xml file. 
So I tried, as you suggested, to configure this dependency in the build.gradle:
...
dependencies {
   implementation "com.gluonhq.attachextended:log:4.0.12"
   runtimeOnly "com.gluonhq.attachextended:log:4.0.12:desktop"
}
...
So as to replace the pom.xml
```
    <dependency>
        <groupId>com.gluonhq.attachextended</groupId>
        <artifactId>log</artifactId>
        <version>4.0.12</version>
    </dependency>
    <dependency>
        <groupId->com.gluonhq.attachextended</groupId>
        <artifactId>log</artifactId>
        <version>4.0.12</version>
        <classifier>desktop</classifier>
        <scope>runtime</scope>
    </dependency>
```

but the error is still present.

**Comment by jperedadnr** [comment]
What error??
Can you post your build.gradle and the logs with the stacktrace?

**Comment by websystemtechnology** [comment]
plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.0.11'
    id 'com.gluonhq.gluonfx-gradle-plugin' version '1.0.11'
}
repositories {
	mavenCentral()
	mavenLocal()
	maven {
        url 'https://oss.sonatype.org/content/repositories/snapshots'
    }
    maven {
        url 'https://nexus.gluonhq.com/nexus/content/repositories/releases'
    }
}
dependencies {
	compile fileTree(dir: '../gfx_mglib/build/libs', include: ['*.jar']) 
	compile fileTree(dir: '../gfx_nowapp/build/libs', include: ['*.jar']) 
    compile 'com.gluonhq:charm:6.0.6'
    compile group: 'com.jfoenix', name: 'jfoenix', version: '9.0.10'
    compile group: 'eu.hansolo', name: 'Medusa', version: '11.7'
	compile group: 'com.gluonhq', name: 'maps', version: '2.0.0-ea+5'
	compile group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.10.2'  
	compile group: 'javax.ws.rs', name: 'javax.ws.rs-api', version: '2.0'
	compile group: 'org.openjfx', name: 'javafx-controls', version: '12'
	compile group: 'org.controlsfx', name: 'controlsfx', version: '11.1.1'
	compile group: 'org.glassfish', name: 'jakarta.json', version: '1.1.6' 
	compile group: 'org.glassfish.jaxb', name: 'jaxb-runtime', version: '2.3.1'

	compile group: 'com.gluonhq.attachextended', name: 'log', version: 'unspecified'
	runtimeOnly group: 'com.gluonhq.attachextended', name: 'log', version: 'unspecified', classifier: 'desktop'
}
javafx {
    version = '18-ea+9'
    modules = [ 'javafx.controls' ]
}
gluonfx {
	mainClassName = 'it.ws.app.MainApplication'
	target = 'desktop'
    attachConfig {
        version = "4.0.14-SNAPSHOT"
        services 'settings', 'display', 'browser', 'cache', 'share', 'lifecycle', 'statusbar', 'storage', 'local-notifications', 'device', 'connectivity', 'dialer', 'orientation', 'push-notifications', 'runtime-args', 'pictures', 'barcode-scan', 'position'
    }
}

**Comment by jperedadnr** [comment]
I still don’t know what commands are you running, and what errors are you facing. Please update your post accordingly (and with the correct formatting)

**Comment by websystemtechnology** [comment]
> I still don’t know what commands are you running, and what errors are you facing. Please update your post accordingly (and with the correct formatting)

Attached is the error log
[ErrorLog.txt](https://github.com/gluonhq/AttachExtended/files/7971276/ErrorLog.txt)

**Comment by jperedadnr** [comment]
Why do you use `unespecified` in 
```
	compile group: 'com.gluonhq.attachextended', name: 'log', version: 'unspecified'
	runtimeOnly group: 'com.gluonhq.attachextended', name: 'log', version: 'unspecified', classifier: 'android'
```
do you get 4.0.12?

From the logs, this is the error you get that causes the crash:
```
AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "Java_com_sun_javafx_font_FontConfigManager_getFontConfig" referenced by "/data/app/~~Ekl9-l-f0ztZGC6FGZ_pHA==/it.wstech.demoservice-SK2Q_eJkwNH8c0DEXTcF_Q==/lib/arm64/libsubstrate.so"...
01-31 14:58:46.465 18656 18656 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
01-31 14:58:46.465 18656 18656 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
01-31 14:58:46.465 18656 18656 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1664)
01-31 14:58:46.465 18656 18656 E AndroidRuntime:        at com.gluonhq.helloandroid.MainActivity.surfaceCreated(MainActivity.java:104)
01-31 14:58:46.465 18656 18656 E AndroidRuntime:        at android.view.SurfaceView.updateSurface(SurfaceView.java:1265)
```

It is weird, JavaFX classes should be reachable.

Can you remove
```
compile group: 'org.openjfx', name: 'javafx-controls', version: '12'
```
from the build.gradle and try again?
If it doesn't work, run:
`gradlew nativeRunAgent` and explore the application on your desktop,
and then `gradlew nativeBuild nativePackage`

**Comment by websystemtechnology** [comment]
I did a new test, removed the javafx-controls dependency and changed the version of the aattachextended from unspecified to 4.0.12.
Rerun the build, package and installed the app on the smartphone, but the app does not start. Attached is the new log, but it is practically identical to the previous one.
Next, I ran the nativeRunAgent and on the desktop the app works fine.

[ErrorLog2.txt](https://github.com/gluonhq/AttachExtended/files/7977790/ErrorLog2.txt)

**Comment by jperedadnr** [comment]
You didn't follow the steps I mentioned, you need to run nativeRunAgent **_before_** you build. See docs https://docs.gluonhq.com/#_goals (it is for the Maven plugin, but the idea is the same):

**Comment by websystemtechnology** [comment]
I run nativaRunAgent before the build, and I get the same problem.
I attach the runAgent log.

[LogRunAgent.txt](https://github.com/gluonhq/AttachExtended/files/7977894/LogRunAgent.txt)

**Comment by websystemtechnology** [comment]
> You didn't follow the steps I mentioned, you need to run nativeRunAgent **_before_** you build. See docs https://docs.gluonhq.com/#_goals (it is for the Maven plugin, but the idea is the same):

Is goal [install ](https://docs.gluonhq.com/#_gluonfxinstall) always necessary?
I've never done it, it's for use when creating an attach-extended (https://github.com/gluonhq/AttachExtended)?

**Comment by jperedadnr** [comment]
Install (nativeInstall) let’s you deploy directly to your phone. It is not mandatory but saves you the trouble of installing the apk by other means.

**Comment by jperedadnr** [comment]
The error is different now:
```
AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__android_log_print" referenced by "/data/app/~~dgsow9GhHohL6tIK3WWtVw==/it.wstech.demoservice-DNnutEmghNUFX7ex4sE4tw==/lib/arm64/libsubstrate.so"...
02-01 11:49:35.006 15884 15884 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
02-01 11:49:35.006 15884 15884 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
02-01 11:49:35.006 15884 15884 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1664)
02-01 11:49:35.006 15884 15884 E AndroidRuntime:        at com.gluonhq.helloandroid.MainActivity.surfaceCreated(MainActivity.java:104)
02-01 11:49:35.006 15884 15884 E AndroidRuntime:        at android.view.SurfaceView.updateSurface(SurfaceView.java:1265)
```

"__android_log_print" comes from Android NDK, so make sure you have the correct version (usually a recent version 21.0+ should be enough).

**Comment by websystemtechnology** [comment]
> "__android_log_print" comes from Android NDK...

I also reset all the androidSDK and repeated the whole procedure.
The Android NDK and all plugins are downloaded automatically during the build.
However I always have the same errere described in the previous posts.

**Comment by jperedadnr** [comment]
What Android device do you have? Is it possible that you post the APK here so I can test it on mine?

**Comment by websystemtechnology** [comment]
Various smartphones such as Samsung, Sony, Redmi with android versions 10 and 11.

**Comment by websystemtechnology** [comment]
https://drive.google.com/drive/folders/141EXWXWwrO0ne_kNtoZkbj8Ud6qOE10c

**Comment by jperedadnr** [comment]
The app starts on my Pixel XL (Android 10), and doesn't crash. I don't get too far, but I see some issues:

[log.txt](https://github.com/gluonhq/AttachExtended/files/7989739/log.txt)

**Comment by websystemtechnology** [comment]
For the tests I use a Readmi with version Android 11. Could the crash depend on the version?

**Comment by websystemtechnology** [comment]
what can i do to avoid the crash problem? maybe by updating the version of graalVM I could fix it?
